# Generated by Django 3.1.2 on 2020-10-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resa', '0003_auto_20201029_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diver',
            name='reservation',
            field=models.ManyToManyField(blank=True, to='resa.Dive'),
        ),
    ]
